name: CI

$:	?
	"resource": "/c:/Users/conte/.vscode/extensions/0/MindApp/.vscode/launch.json",
	"owner": "_generated_diagnostic_collection_name_#4",
	0:.
	"message": "Expected a JSON object, array or literal.",
	"source": "jsonc",
	"startLineNumber": 1,
	"startColumn": 1,
 jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: #2
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.10.3
          otp-version: 22.3
      - name: Install Xvfb
        run: ## -.c.cc.
          sudo apt-get install xvfb
      - name: Start Xvfb
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Resolve elixir-ls dependencies
        run: |
          cd elixir-ls
          mix deps.get
      - name: Resolve vscode-elixir-ls dependencies
        run: |
          npm install
          npm run lint
          npm run check-formatting
          npm run compile
      - name: Run tests
        run: |
          npm test
        env:
          DISPLAY: :1782.1
